[package]
name = "scope_tracker"
version = "0.1.0"

[profile.dev]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
incremental = false
lto = true
panic = "abort"

[dependencies]
avr-libc = "0.1.3"
ruduino = {git = "https://github.com/avr-rust/ruduino"}
